= Licencia
:encoding: utf-8
:lang: es
:doctype: book

link:LICENSE.adoc[Español] / link:LICENSE.en.adoc[English]

== LICENCIA

Este software depende de las siguientes librerías y no funciona sin ellas:

Live2D Cubism SDK::
Librería utilizada para ejecutar archivos creados con Live2D Editor.

Live2D Cubism NativeFramework::
Librería que facilita el uso del SDK.

Por lo tanto, como usuario debes cumplir con las siguientes licencias al construir y usar este software.

=== Live2D Open Software License
Live2D Cubism Components está disponible bajo Live2D Open Software License.

* https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html[Live2D Open Software License Agreement]
* https://www.live2d.com/eula/live2d-open-software-license-agreement_jp.html[Live2D Open Software 使用許諾契約書]

Al publicar aplicaciones creadas con GDCubism, se deben cumplir los siguientes acuerdos.

=== Live2D Proprietary Software License
Live2D Cubism Core está disponible bajo Live2D Proprietary Software License.

* https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_en.html[Live2D Proprietary Software License Agreement]
* https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_jp.html[Live2D Proprietary Software 使用許諾契約書]

[IMPORTANT]
====
Solo la porción del repositorio de GDCubism que está disponible públicamente está cubierta por la licencia MIT de GDCubism.

Ten en cuenta que durante el proceso de compilación se enlazará con la librería de Live2D.
====

=== Información de licencias

==== Live2D Cubism SDK / Cubism Native Framework

Para Live2D Cubism Components y CubismNativeFramework, consulta la información de licencia en:

* https://github.com/Live2D/CubismNativeFramework[]

==== GDCubism

MIT License

Copyright (c) 2023 MizunagiKB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
